# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobufs/sensors.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'protobufs/sensors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17protobufs/sensors.proto\x12\rstreet_manata\"H\n\x03Gps\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x12\x10\n\x08latitude\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"?\n\x03Imu\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x12\t\n\x01w\x18\x05 \x01(\x02\"#\n\x05Photo\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\"H\n\x05Video\x12\x12\n\nstart_time\x18\x01 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\x12\x0b\n\x03\x66ps\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\t\"\xcf\x01\n\nSensorData\x12\x0e\n\x06verion\x18\x01 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\t\x12\x1f\n\x03gps\x18\x03 \x03(\x0b\x32\x12.street_manata.Gps\x12\x1f\n\x03imu\x18\x04 \x03(\x0b\x32\x12.street_manata.Imu\x12\x14\n\x0c\x63\x61mera_index\x18\x05 \x01(\x05\x12$\n\x06photos\x18\x06 \x03(\x0b\x32\x14.street_manata.Photo\x12#\n\x05video\x18\x07 \x01(\x0b\x32\x14.street_manata.Videob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobufs.sensors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPS']._serialized_start=42
  _globals['_GPS']._serialized_end=114
  _globals['_IMU']._serialized_start=116
  _globals['_IMU']._serialized_end=179
  _globals['_PHOTO']._serialized_start=181
  _globals['_PHOTO']._serialized_end=216
  _globals['_VIDEO']._serialized_start=218
  _globals['_VIDEO']._serialized_end=290
  _globals['_SENSORDATA']._serialized_start=293
  _globals['_SENSORDATA']._serialized_end=500
# @@protoc_insertion_point(module_scope)
